repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        files: ^Patres/.*\.py$
        exclude: ^Patres/venv/
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        files: ^Patres/.*\.py$
        exclude: ^Patres/venv/
        args: ["--fix"]
      - id: ruff-format
        files: ^Patres/.*\.py$
        exclude: ^Patres/venv/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        files: ^Patres/.*\.py$
        exclude: ^Patres/(venv|alembic)/
