[tool.black]
line-length = 88
target-version = ["py312"]

[tool.ruff]
line-length = 88
target-version = "py312"
exclude = ["migrations", "venv", "__pycache__"]


[tool.ruff.lint]
select = ["E", "F", "I", "N"]
ignore = ["E203"]


[tool.mypy]
python_version = "3.12"
strict = false
ignore_missing_imports = true
disallow_untyped_defs = false

