# Generated by Django 4.2.11 on 2024-10-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onlineshop", "0003_sale_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="totalCost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
